# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
#- task: NodeTool@0
#  inputs:
#    versionSpec: '10.x'
#  displayName: 'Install Node.js'

#- script: |
#    npm install -g @angular/cli
#    npm install
#    ng build --prod
#  displayName: 'npm install and build'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
      
      echo 'Hello world'
      pwd
      ls -la
      cd src
      ls -al 
      
- task: Npm@1
  displayName: '***** npm install *****'
  inputs:
    command: 'install'
    workingDir: './'

- task: Npm@1
  inputs:
    command: 'custom'
    workingDir: './'
    customCommand: 'run build --prod'


- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: './dist'
    ArtifactName: 'web-theLionKing'
    publishLocation: 'Container'
